// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgqqdhghalznohlikwrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRncXFkaGdoYWx6bm9obGlrd3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTgzMjUsImV4cCI6MjA2NTU3NDMyNX0.AeeiEv09SpbE2azt9PnpJGjhA5ytI6Q0Ny07u1hwUYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);